### ISSUE TITLE
Swap `stockAmount` with `amount` for consistency.

### ISSUE THREAD

**Issue by j0sephh123** [momozor/quaremain#13]
When we are creating a new stock, we need to use `stockAmount` property. ( __first code snippet__ )
When we get response from the back-end, we get `stock` ( __second code snippet__ )

```
class Stock {
  constructor(stock) {
    this.name = stock.name;
    this.description = stock.description;
    this.stockAmount = stock.stockAmount;
    this.costPerPackage = stock.costPerPackage;
    this.stockCategory = stock.stockCategory;
  }
}

class Water extends Stock {
    ...
    this.millilitrePerPackage = stock.millilitrePerPackage;
}

class Food extends Stock {
    ...
    this.caloriesPerPackage = stock.caloriesPerPackage;
}
```

```
    {
      "id": 3,
      "name": "Bananas",
      "description": "......",
      "amount": 15,
      "costPerPackage": 2.99,
      "caloriesPerPackage": 111
    },
// for water it's - millilitrePerPackage
```

**Comment by momozor** [comment]
Alright, I'll try to work on this later.

Reference - https://github.com/momozor/quaremain/blob/fc0f154ab51ae9432d3ffed6f7efb229d99f75cf/src/web.lisp#L149

**Comment by momozor** [comment]
Alright. Fixed at https://github.com/momozor/quaremain/commit/b524cfbfdcd78ba28572ec09d329bcc2f425b430

**Comment by momozor** [comment]
While we're at it, do you think we should rename *PerPackage to *PerStock too?

**Comment by j0sephh123** [comment]
`*PerPackage -> *PerStock` - yes

`millilitre -> millilitres` - yes, but both are for the code  

`<td>{{ stock.millilitrePerPackage }}ML</td>` no matter what is the name, we display __ML__
