### ISSUE TITLE
Creating a stock - modify returned registeredStock suggestion

### ISSUE THREAD

**Issue by j0sephh123** [momozor/quaremain#17]
When creating a new stock:
- this is the stock object we send to the API's `list/create` endpoint
```
{
    amount: '1',
    caloriesPerStock: '1',
    costPerStock: '1.00',
    description: '',
    name: 'foodStock',
    stockCategory: 'food'
}
```

- this is the `registeredStock` we get:
```
{
    stockCategory: 'food',
    name: 'foodStock',
    description: '',
    amount: '1',
    costPerStock: '1.00',
    caloriesPerStock: '1',
    millilitresPerStock: ''
}
```

Creating a `water` stock also has `caloriesPerStock` returned
Creating a `medicine` stock has both `caloriesPerStock` and `millilitresPerStock` returned

My suggestion is to have the same response as when we make a request for one stock
`list/show/1?stockCategory=food`  
```
{
    "id": 1,
    "name": "foodStock",
    "description": "",
    "amount": 1,
    "costPerStock": 1,
    "caloriesPerStock": 1
}
```

The reasoning is that we can add the returned stock to the stocks list without having to do a new request for all the stocks of certain type. We can't do that now, since we don't have the __ID__.  
Also, we there is no need get `calories` when we are creating a water type.

**Comment by momozor** [comment]
Fixed at https://github.com/momozor/quaremain/commit/068e3ac29ccf04b4669fdcf8a7e247bf850a1573

**Comment by j0sephh123** [comment]
Actually, on creating a new stock: 
- now we are not returning redundant data
- but still __id__ isn't returned

**Comment by momozor** [comment]
My bad. Thanks for pointing that out.

Fixed at - https://github.com/momozor/quaremain/commit/4796daad58111d0e1d4ada5ea158e57d6cfca2ef

**Comment by j0sephh123** [comment]
Thank you
