### ISSUE TITLE
API endpoint for count

### ISSUE THREAD

**Issue by j0sephh123** [momozor/quaremain#18]
Example endpoint: `/foods/count`
Expected result: number - the total number of stocks 

Would be very useful in __pagination__ for calculating if there are more stocks available

**Comment by momozor** [comment]
So you want this functionality for a category `/api/stocks/foods` or actually for everything in a single query? `/api/stocks/`

**Comment by j0sephh123** [comment]
> So you want this functionality for a category `/api/stocks/foods` or actually for everything in a single query? `/api/stocks/`
> 
> I could just return in the response by default for either of them, something like this `totalStocks: 92`

Yeah, I wrote it ambiguously.
The request was to have the number of all __foods__, so only for the specific category.
Although `totalStocks` would definitely come in use too, let's say for statistics page.

**Comment by momozor** [comment]
> > So you want this functionality for a category `/api/stocks/foods` or actually for everything in a single query? `/api/stocks/`
> > I could just return in the response by default for either of them, something like this `totalStocks: 92`
> 
> Yeah, I wrote it ambiguously.
> The request was to have the number of all **foods**, so only for the specific category.
> Although `totalStocks` would definitely come in use too, let's say for statistics page.

Alright, I'll make for both of them.

**Comment by momozor** [comment]
Fixed at - https://github.com/momozor/quaremain/commit/ad5423cbeee5e96db4c9f6d681bc35ca0de7de7b

**Comment by momozor** [comment]
To be fair, naming it to `totalRows` should be more accurate, don't you think?

**Comment by j0sephh123** [comment]
> To be fair, naming it to `totalRows` should be more accurate, don't you think?

Sorry for the late reply, didn't see it.. Yeah, probably.
