### ISSUE TITLE
On submitting a new stock, return the newly created stock

### ISSUE THREAD

**Issue by j0sephh123** [momozor/quaremain#7]
Currently, when we create a new stock, we get `data: {status: 200}`
It would be nice to also return the newly created stock. Then we could add it to the existing stocks array instead of making a new request for all the stock items.
```
      let result = await api.create(submitData);

      // for now we get only result.status, so, we fetch the whole
      // dataset again in the future probably just get the newly created
      // stock and add it do the existing stocks
      if(result.status === 200) {
        dispatch('loadStocks', state.activeTab)
      }
      etc..
```

**Comment by momozor** [comment]
Alright. This feature has been added at commit https://github.com/momozor/quaremain/commit/55093adfbfdf7b7b8103e855e71ad5fdd3e0860f.

The success response for create api will return a new key `registeredStock`.

Keys that are not relevant to the stock  (for example, millilitrePerPackage) will return null instead.

For example, 

```json

{
    "status": 200,
    "registeredStock": {
        "stockCategory": "food",
        "name": "ohohoho",
        "description": "jajweajkwjkeaweaeawaw",
        "amount": "wyattt",
        "costPerPackage": "434.2",
        "caloriesPerPackage": "9934",
        "millilitrePerPackage": null
    }
}

```

If you have more suggestion on this feature, feel free to re-open this.
